Marketplace/Marketplace/urls.py
from django.conf import settings      #only for development to see images
from django.conf.urls.static import static #only for development to see images
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #only for development to see images

Marketplace/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

Marketplace/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views  #import for login, no need views
from .forms import LoginForm




app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    
]

Marketplace/dashboard/urls.py
from django.urls import path
from . import views


app_name='dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

Marketplace/item/urls.py
from django.urls import path
from . import views

app_name ='item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

Marketplace/core/models.py
from django.db import models

# Create your models here.

Marketplace/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-3 px-5 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-3 px-5 rounded-xl'
    }))



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-3 px-5 rounded-xl'
    }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-3 px-5 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-3 px-5 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Re-enter your password',
        'class': 'w-full py-3 px-5 rounded-xl'
    }))


Marketplace/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.models import User




def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form= SignupForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request, user)
            
            return redirect('/login/')
    else:
        form= SignupForm()
    
    form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form
    })

def myaccount(request):
    return render(request, 'core/myaccount.html')

        

Marketplace/core/templates/core/base.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %} {% endblock %} | Marketplace </title>
</head>

<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-blue-200">
        <a href="/" class="text-2xl bg-gradient-to-r from-green-400 to-blue-500 hover:from-pink-500 hover:to-yellow-500"
            style="font-weight: 500; color:white; padding: 20px;border-radius: 10px;">Marketplace</a>

        <div class="space-x-6">
            <a href="{% url 'item:new' %}"
                class="px-6 py-3 text-lg font-medium bg-gray-500 text-white rounded-xl hover:bg-gray-600">New items</a>
            <a href="{% url 'item:items' %}"
                class="px-6 py-3 text-lg font-medium bg-gray-100 rounded-xl hover:text-blue-700">Search</a>
            <!--Browse link-->

            {% if request.user.is_authenticated %}
            <a href="{% url 'conversation:inbox' %}"
                class="px-6 py-3 text-lg font-medium bg-blue-500 text-white rounded-xl hover:bg-blue-700">Inbox</a>
            <a href="{% url 'dashboard:index' %}"
                class="px-6 py-3 text-lg font-medium bg-gray-400 text-white rounded-xl hover:bg-gray-600">Dashboard</a>
            <a href="{% url 'core:myaccount' %}"
                class="px-6 py-3 text-lg font-medium bg-red-400 text-white rounded-xl hover:bg-red-600">Logout</a>
            {% else %}
            <a href="{% url 'core:signup' %}"
                class="px-6 py-3 text-lg font-medium bg-blue-500 text-white rounded-xl hover:bg-blue-700">Sign Up</a>
            <a href="{% url 'core:login' %}"
                class="px-6 py-3 text-lg font-medium bg-gray-500 text-white rounded-xl hover:bg-gray-600">Login</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content%}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-700">

        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400"> About </h3>

            <p class="text-lg text-gray-500">Marketplace founded in 1922 by Hussein Dabs and his brother Daniel. <br>
                We specialize mostly in the food industry, bringing you the freshest natural ingredients.
            </p>
        </div>

        <div class="w-1/4">
            <h3 class="mb-5 font-semibold text-gray-400"> Menu </h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700"> About </a></li>
                <li><a href="{% url 'core:contact' %}" class=" text-lg text-teal-500 hover:text-teal-700"> Contact
                        us</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700"> Privacy </a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700"> Term of use </a></li>
            </ul>
        </div>

    </footer>

</body>

</html>

Marketplace/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}


{% block content%}
<h1 class="text-xl" style="font-weight: 500;">
    Contact and projects below
</h1> <br><br><br>

<h2>
        <a  href="https://www.linkedin.com/in/harvey-hussein-deaibes-080756121/">LinkedIn Link: <u>www.linkedin.com/in/harvey-hussein-deaibes-080756121</u></a><br><br>
        <a href="https://github.com/MyBestHub">GitHub Link: <u> https://github.com/MyBestHub</u></a><br><br>
        Email contact: hussein_deaibes1@hotmail.com    
</h2>
{% endblock %}

Marketplace/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}


{% block content%}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500"> Price {{ item.price }}$</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">  <!--Recently added on the main page, so when I click on one of the categories, 
                                                                                                        it direct me to the right pages, copied from item folder in items.html-->
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500"> {{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}


    
    



Marketplace/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounder-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-5">
            <label class="inline-block mb-2"> Username</label> <br>
            {{ form.username }}<br><br>
            
            <label class="inline-block mb-2">Password</label> <br>
            {{ form.password }}<br><br>
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-600 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}



Marketplace/core/templates/core/myaccount.html
{% extends 'core/base.html' %}

{% block title %}My account{% endblock %}

{% block content %}
<h1 class="text-2xl">Click again to logout</h1>

<a href="{% url 'core:logout' %}"
    class="mt-6 inline-block py-4 px-8 bg-red-400 text-white rounded-xl hover:bg-red-600">Log out</a>
{% endblock %}

Marketplace/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign Up {% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounder-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-5">
            <label class="inline-block mb-2">Create your username</label> <br>
            {{ form.username }}<br><br>
            <label class="inline-block mb-2">Enter your email</label> <br>
            {{ form.email }}<br><br>
            <label class="inline-block mb-2">Password</label> <br>
            {{ form.password1 }}<br><br>
            <label class="inline-block mb-2">Repeat password</label> <br>
            {{ form.password2 }}<br><br>

        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-600 rounded-xl text-white">Submit</button>
    </form>
</div>

<br><br>

<div class="w-1/6 my-4 mx-auto p-2 bg-cyan-100 rounded-3xl">
    <h2>Already have an account? </h2><br> <h2><a href="{% url 'core:login' %}"><h2 class="mb-6 text-xl"><p class="text-blue-500">Click Login</p></h2></a></h2>
</div>
{% endblock %}

